- name: Sprawdz czy openldap-servers present
  dnf:
    name: openldap-servers
    state: present  # Upewnij się, że pakiet jest zainstalowany
    allowerasing: true
    allow_downgrade: true

- name: Sprawdz czy openldap-clients present
  dnf:
    name: openldap-clients
    state: present  # Upewnij się, że pakiet jest zainstalowany
    allowerasing: true
    allow_downgrade: true

- name: Uruchom usługę slapd
  systemd:
    name: slapd
    state: started

- name: Install pip
  dnf:
    name: python3-pip
    state: present  # Upewnij się, że pakiet jest zainstalowany

- name: Generate slappasswd password
  command: "slappasswd -s {{ vault_secret }}"
  register: slappasswd_output
  changed_when: false  # Nie oznaczaj jako zmienione, nawet jeśli polecenie jest wykonywane za każdym razem

- name: Display encrypted password
  debug:
    var: slappasswd_output.stdout_lines[0]

- name: Prepare chrootpw.ldif file
  template:
    src: templates/chrootpw.ldif.j2
    dest: /tmp/chrootpw.ldif

- name: Prepare chdomain.ldif.ldif file
  template:
    src: templates/chdomain.ldif.j2
    dest: /tmp/chdomain.ldif

- name: Prepare basedomain.ldif file
  template:
    src: templates/basedomain.ldif.j2
    dest: /tmp/basedomain.ldif

- name: Prepare mod_ssl.ldif file
  template:
    src: templates/mod_ssl.ldif.j2
    dest: /tmp/mod_ssl.ldif

- name: Get rid of an old entry
  ldap_entry:
    dn: ou=stuff,dc=example,dc=com
    state: absent
    server_uri: ldap://localhost/
    bind_dn: cn=admin,dc=example,dc=com
    bind_pw: '{{ vault_secret }}'