- name: Ustaw hostname
  hostname:
    name: '{{ server_hostname }}'

- name: Update yum
  dnf:
    name: '*'
    state: latest

- name: Skonfiguruj repozytorium CRB
  ini_file:
    path: /etc/yum.repos.d/crb.repo  # Ścieżka do pliku repozytorium CRB
    section: crb
    option: enabled
    value: 1

- name: Zainstaluj epel-release
  dnf:
    name: epel-release
    state: present  # Upewnij się, że pakiet jest zainstalowany

- name: Zainstaluj epel-next-release
  dnf:
    name: epel-next-release
    state: present  # Upewnij się, że pakiet jest zainstalowany

- name: Zainstaluj epel-next-release
  dnf:
    name: mod_ssl
    state: present  # Upewnij się, że pakiet jest zainstalowany