---
- name: "Accountswich"
  hosts: localhost
  vars: 
    default_region: eu-central-1

  tasks:  
    - sts_assume_role:
        role_arn: "arn:aws:iam::562476416241:role/admin"
        role_session_name: "ec2_list"
        region: "eu-central-1"
        mfa_serial_number: "arn:aws:iam::573699462807:mfa/damian.kasyan.extern@ergo.com"
        mfa_token: 802374 
      register: assumed_role

    - shell: aws s3 ls
      environment:
          AWS_ACCESS_KEY_ID: "{{ assumed_role.sts_creds.access_key }}"
          AWS_SECRET_ACCESS_KEY: "{{ assumed_role.sts_creds.secret_key }}"
          AWS_SESSION_TOKEN: "{{ assumed_role.sts_creds.session_token }}"
          AWS_DEFAULT_REGION: "{{ default_region }}"

    - debug:
        msg: "{{ out }}"